name: CI-master
 
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - 'data/**'
      - 'LICENSE'
      - 'changelog'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'doc/**'
      - 'data/**'
      - 'LICENSE'
      - 'changelog'

  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted,gpu]
    
    steps:
      - uses: actions/checkout@v2
        with:
         submodules: 'recursive'
         
      # - run: module load gcc/7.3.0
      # - run: gcc -v
      # - run: g++ -v
      # - run: module load cuda/10.1
      # - run: nvcc --version
      # - run: module load cmake/3.17.0
      - name: compilation
        run: chmod 755 ./build.py && ./build.py compat
      - name: test with gzip option activated 
        run: |
          ./bin/cusz -t f32 -m r2r -e 1.0e-3.0 -i ./data/cesm-CLDHGH-3600x1800 -l 3600,1800 --gzip -z -x --origin ./data/cesm-CLDHGH-3600x1800 --gtest
          ./bin/cusz -t f32 -m r2r -e 1.0e-4.0 -i ./data/exafel-59200x388 -l 59200,388 --gzip -z -x --origin ./data/exafel-59200x388 --gtest
          ./bin/cusz -t f32 -m r2r -e 1.0e-3.0 -i ./data/hurr-CLOUDf48-500x500x100 -D hurricane --gzip -z -x --origin ./data/hurr-CLOUDf48-500x500x100 --gtest
      - name: test with nvcomp option activated
        run: |
          ./bin/cusz -t f32 -m r2r -e 1.0e-3.0 -i ./data/cesm-CLDHGH-3600x1800 -l 3600,1800 --nvcomp -z -x --origin ./data/cesm-CLDHGH-3600x1800 --gtest
          ./bin/cusz -t f32 -m r2r -e 1.0e-4.0 -i ./data/exafel-59200x388 -l 59200,388 --nvcomp -z -x --origin ./data/exafel-59200x388 --gtest
          ./bin/cusz -t f32 -m r2r -e 1.0e-3.0 -i ./data/hurr-CLOUDf48-500x500x100 -D hurricane --nvcomp -z -x --origin ./data/hurr-CLOUDf48-500x500x100 --gtest
      - name: test with gzip and nvcomp option both activated
        run: |
          ./bin/cusz -t f32 -m r2r -e 1.0e-3.0 -i ./data/cesm-CLDHGH-3600x1800 -l 3600,1800 --gzip --nvcomp -z -x --origin ./data/cesm-CLDHGH-3600x1800 --gtest
          ./bin/cusz -t f32 -m r2r -e 1.0e-4.0 -i ./data/exafel-59200x388 -l 59200,388 --gzip --nvcomp -z -x --origin ./data/exafel-59200x388 --gtest
          ./bin/cusz -t f32 -m r2r -e 1.0e-3.0 -i ./data/hurr-CLOUDf48-500x500x100 -D hurricane --gzip --nvcomp -z -x --origin ./data/hurr-CLOUDf48-500x500x100 --gtest
